@extends('layouts.dswd')
@section('heading', 'F1KD Beneficiary')
@section('content')
<header class="account-heading"><div><p class="account-kicker">F1KD BENEFICIARY</p><h1>{{ $beneficiary->name }}</h1><p>Monthly compliance summary</p></div><a class="dswd-button secondary" href="{{ route('dswd.f1kd.index', ['month'=>$beneficiary->month]) }}">Back to monitoring</a></header>
<section class="admin-card"><dl class="dswd-details">
@foreach(['household'=>'Household reference','beneficiary_id'=>'Beneficiary ID','sex'=>'Sex','barangay'=>'Barangay','municipality_city'=>'Municipality / City','month'=>'Reporting period'] as $field=>$label)<div><dt>{{ $label }}</dt><dd>{{ $beneficiary->$field ?: 'Not recorded' }}</dd></div>@endforeach
<div><dt>Classification</dt><dd>{{ \App\Support\F1kdCompliance::CLASSES[$beneficiary->classification] }}</dd></div><div><dt>Current F1KD status</dt><dd>@include('dswd.f1kd.badge', ['status'=>$beneficiary->status])</dd></div>
</dl><p class="dswd-note">Household reference uses the Project INAY mother registration ID; it is not an official DSWD household number. Last updated: {{ $beneficiary->updated_at?->format('M j, Y H:i') ?? 'Awaiting verification' }}.</p>
<form method="get" class="dswd-actions"><label>Reporting period <input type="month" name="month" value="{{ $beneficiary->month }}" max="{{ now()->format('Y-m') }}" required></label><button class="dswd-button secondary">View period</button></form></section>
<section class="admin-card"><h2>Compliance checklist</h2><div class="dswd-table-wrap"><table class="dswd-table"><thead><tr><th scope="col">F1KD condition</th><th scope="col">Status</th></tr></thead><tbody>@foreach($conditions as $key=>$label)<tr><td>{{ $label }}</td><td>@include('dswd.f1kd.badge', ['status'=>$beneficiary->checklist[$key] ?? 'verification'])</td></tr>@endforeach</tbody></table></div></section>
<section class="admin-card"><h2>Areas for verification</h2>@if($beneficiary->verification)<ul>@foreach($beneficiary->verification as $label)<li>{{ $label }}</li>@endforeach</ul>@else<p>No areas awaiting verification.</p>@endif</section>
<section class="admin-card"><h2>Previous monthly monitoring history</h2><div class="dswd-table-wrap"><table class="dswd-table"><thead><tr><th scope="col">Month</th><th scope="col">F1KD status</th><th scope="col">Last updated</th><th scope="col">Action</th></tr></thead><tbody>@forelse($history as $record)<tr><td>{{ $record->reporting_month->format('Y-m') }}</td><td>@include('dswd.f1kd.badge', ['status'=>$record->status])</td><td>{{ $record->updated_at->format('M j, Y H:i') }}</td><td><a href="{{ route('dswd.f1kd.show', ['subject'=>$beneficiary->key, 'month'=>$record->reporting_month->format('Y-m')]) }}">View checklist</a></td></tr>@empty<tr><td colspan="4">No previous monthly records.</td></tr>@endforelse</tbody></table></div>@include('dswd.partials.pagination', ['paginator'=>$history])</section>
@endsection