<?php

return [
    'categories' => [
        ['key' => 'government_hospital', 'label' => 'Government Hospital'],
        ['key' => 'private_hospital', 'label' => 'Private Hospital'],
        ['key' => 'maternity_clinic', 'label' => 'Maternity Clinic'],
        ['key' => 'lying_in_clinic', 'label' => 'Lying-In Clinic'],
        ['key' => 'birthing_center', 'label' => 'Birthing Center'],
        ['key' => 'obgyn_clinic', 'label' => 'Women\'s Health / OB-GYN Clinic'],
    ],

    'facilities' => [
        [
            'id' => 'community-general-hospital-san-pablo',
            'name' => 'Community General Hospital of San Pablo City',
            'category_key' => 'private_hospital',
            'category' => 'Private Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Emergency availability may vary. Call before going.',
            'latitude' => 14.0696,
            'longitude' => 121.3256,
            'maternal_services' => ['Emergency Care', 'General Consultation', 'OB-GYN Referral', 'Pediatrics Referral'],
        ],
        [
            'id' => 'san-pablo-colleges-medical-center',
            'name' => 'San Pablo Colleges Medical Center',
            'category_key' => 'private_hospital',
            'category' => 'Private Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Hospital hours may vary by department.',
            'latitude' => 14.0668,
            'longitude' => 121.3269,
            'maternal_services' => ['Emergency Room', 'OB-GYN Services', 'Pediatrics', 'Diagnostic Services'],
        ],
        [
            'id' => 'san-pablo-city-doctors-hospital',
            'name' => "San Pablo City Doctors' Hospital",
            'category_key' => 'private_hospital',
            'category' => 'Private Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Hospital hours may vary by department.',
            'latitude' => 14.0719,
            'longitude' => 121.3234,
            'maternal_services' => ['Emergency Care', 'OB-GYN Consultation', 'Delivery Referral', 'Pediatrics'],
        ],
        [
            'id' => 'san-pablo-city-general-hospital',
            'name' => 'San Pablo City General Hospital',
            'category_key' => 'government_hospital',
            'category' => 'Government Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Emergency availability may vary. Call before going.',
            'latitude' => 14.075,
            'longitude' => 121.3198,
            'maternal_services' => ['Emergency Care', 'Maternal Referral', 'General Medicine', 'Public Health Desk'],
        ],
        [
            'id' => 'san-pablo-city-district-hospital',
            'name' => 'San Pablo City District Hospital',
            'category_key' => 'government_hospital',
            'category' => 'Government Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Emergency availability may vary. Call before going.',
            'latitude' => 14.0619,
            'longitude' => 121.3199,
            'maternal_services' => ['Emergency Care', 'Outpatient Consultation', 'Maternal Referral', 'Pediatrics Referral'],
        ],
        [
            'id' => 'sts-francis-and-paul-general-hospital',
            'name' => 'Sts. Francis and Paul General Hospital',
            'category_key' => 'private_hospital',
            'category' => 'Private Hospital',
            'address' => 'San Pablo City, Laguna',
            'hotline' => null,
            'tel' => null,
            'hours' => 'Hospital hours may vary by department.',
            'latitude' => 14.0674,
            'longitude' => 121.3312,
            'maternal_services' => ['Emergency Care', 'General Consultation', 'OB-GYN Referral', 'Diagnostic Services'],
        ],
    ],
];