<?php

return [
    'status_labels' => [
        'logged' => 'Logged',
        'within_reference_range' => 'Within Reference Range',
        'for_review' => 'For Review',
        'for_professional_interpretation' => 'For Professional Interpretation',
        'urgent_referral_recommended' => 'Urgent Referral Recommended',
    ],

    'blood_sugar_test_types' => [
        'fasting_plasma_glucose' => 'Fasting plasma glucose',
        'random_blood_glucose' => 'Random blood glucose',
        'ogtt_1_hour' => '1-hour after 75-g OGTT',
        'ogtt_2_hour' => '2-hour after 75-g OGTT',
    ],

    'references' => [
        [
            'title' => 'Philippine Localized MNCHN Manual of Operations',
            'url' => 'https://www.jica.go.jp/project/english/philippines/007/materials/c8h0vm000094iynv-att/materials_02_01.pdf',
        ],
        [
            'title' => 'WHO Recommendations on Antenatal Care',
            'url' => 'https://iris.who.int/bitstreams/6ddf01b4-5b25-4d86-8748-3e86aab01f69/download',
        ],
        [
            'title' => 'WHO Assessment Methods During Pregnancy',
            'url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
        ],
        [
            'title' => 'Philippine Society of Maternal-Fetal Medicine',
            'url' => 'https://psmfm.org/web/professional-resources/',
        ],
    ],

    'thresholds' => [
        [
            'key' => 'blood_pressure.systolic.review_min',
            'measurement' => 'blood_pressure',
            'test_type' => null,
            'threshold_type' => 'review_min',
            'label' => 'Systolic BP review threshold',
            'value' => 140,
            'unit' => 'mmHg',
            'guideline_name' => 'PSMFM Clinical Practice Guidelines on Hypertensive Disorders in Pregnancy',
            'guideline_version' => '2nd Edition, 2024',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Screening threshold only. Repeat measurement and healthcare-worker assessment are required.',
        ],
        [
            'key' => 'blood_pressure.diastolic.review_min',
            'measurement' => 'blood_pressure',
            'test_type' => null,
            'threshold_type' => 'review_min',
            'label' => 'Diastolic BP review threshold',
            'value' => 90,
            'unit' => 'mmHg',
            'guideline_name' => 'PSMFM Clinical Practice Guidelines on Hypertensive Disorders in Pregnancy',
            'guideline_version' => '2nd Edition, 2024',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Screening threshold only. The system must not diagnose hypertension or pre-eclampsia.',
        ],
        [
            'key' => 'blood_pressure.systolic.confirm_min',
            'measurement' => 'blood_pressure',
            'test_type' => null,
            'threshold_type' => 'confirm_min',
            'label' => 'Systolic BP confirmation threshold',
            'value' => 160,
            'unit' => 'mmHg',
            'guideline_name' => 'PSMFM Clinical Practice Guidelines on Hypertensive Disorders in Pregnancy',
            'guideline_version' => '2nd Edition, 2024',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Requires staff confirmation before saving because the value is unusually elevated.',
        ],
        [
            'key' => 'blood_pressure.diastolic.confirm_min',
            'measurement' => 'blood_pressure',
            'test_type' => null,
            'threshold_type' => 'confirm_min',
            'label' => 'Diastolic BP confirmation threshold',
            'value' => 110,
            'unit' => 'mmHg',
            'guideline_name' => 'PSMFM Clinical Practice Guidelines on Hypertensive Disorders in Pregnancy',
            'guideline_version' => '2nd Edition, 2024',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Requires staff confirmation before saving because the value is unusually elevated.',
        ],
        [
            'key' => 'blood_sugar.fasting_plasma_glucose.review_min',
            'measurement' => 'blood_sugar',
            'test_type' => 'fasting_plasma_glucose',
            'threshold_type' => 'review_min',
            'label' => 'Fasting plasma glucose review threshold',
            'value' => 92,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Pregnancy-specific gestational diabetes screening value. Not a diagnosis.',
        ],
        [
            'key' => 'blood_sugar.fasting_plasma_glucose.review_max',
            'measurement' => 'blood_sugar',
            'test_type' => 'fasting_plasma_glucose',
            'threshold_type' => 'review_max',
            'label' => 'Fasting plasma glucose review upper bound',
            'value' => 125,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Values above this remain for professional review and may require referral workflow.',
        ],
        [
            'key' => 'blood_sugar.fasting_plasma_glucose.urgent_min',
            'measurement' => 'blood_sugar',
            'test_type' => 'fasting_plasma_glucose',
            'threshold_type' => 'urgent_min',
            'label' => 'Fasting plasma glucose urgent referral threshold',
            'value' => 126,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Referral support threshold only. The system must not label the mother as diabetic.',
        ],
        [
            'key' => 'blood_sugar.ogtt_1_hour.review_min',
            'measurement' => 'blood_sugar',
            'test_type' => 'ogtt_1_hour',
            'threshold_type' => 'review_min',
            'label' => '1-hour 75-g OGTT review threshold',
            'value' => 180,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Pregnancy-specific screening value after 75-g oral glucose load.',
        ],
        [
            'key' => 'blood_sugar.ogtt_2_hour.review_min',
            'measurement' => 'blood_sugar',
            'test_type' => 'ogtt_2_hour',
            'threshold_type' => 'review_min',
            'label' => '2-hour 75-g OGTT review threshold',
            'value' => 153,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Pregnancy-specific screening value after 75-g oral glucose load.',
        ],
        [
            'key' => 'blood_sugar.ogtt_2_hour.review_max',
            'measurement' => 'blood_sugar',
            'test_type' => 'ogtt_2_hour',
            'threshold_type' => 'review_max',
            'label' => '2-hour 75-g OGTT review upper bound',
            'value' => 199,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Values above this remain for professional review and may require referral workflow.',
        ],
        [
            'key' => 'blood_sugar.ogtt_2_hour.urgent_min',
            'measurement' => 'blood_sugar',
            'test_type' => 'ogtt_2_hour',
            'threshold_type' => 'urgent_min',
            'label' => '2-hour 75-g OGTT urgent referral threshold',
            'value' => 200,
            'unit' => 'mg/dL',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'WHO 2013 criteria, ELENA updated 2023',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Referral support threshold only. The system must not label the mother as diabetic.',
        ],
        [
            'key' => 'blood_sugar.low.review_below',
            'measurement' => 'blood_sugar',
            'test_type' => null,
            'threshold_type' => 'review_below',
            'label' => 'Blood sugar low-value review threshold',
            'value' => 60,
            'unit' => 'mg/dL',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Configurable low-value review guardrail pending local clinical approval.',
        ],
        [
            'key' => 'hemoglobin.review_below',
            'measurement' => 'hemoglobin',
            'test_type' => null,
            'threshold_type' => 'review_below',
            'label' => 'Hemoglobin lower review threshold',
            'value' => 11,
            'unit' => 'g/dL',
            'guideline_name' => 'WHO Recommendations on Antenatal Care',
            'guideline_version' => '2016 ANC recommendations; local facility review required',
            'source_url' => 'https://iris.who.int/bitstreams/6ddf01b4-5b25-4d86-8748-3e86aab01f69/download',
            'notes' => 'Screening threshold only. The system must not diagnose anemia.',
        ],
        [
            'key' => 'hemoglobin.upper_review_min',
            'measurement' => 'hemoglobin',
            'test_type' => null,
            'threshold_type' => 'upper_review_min',
            'label' => 'Hemoglobin upper review threshold',
            'value' => 16.5,
            'unit' => 'g/dL',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Upper threshold is intentionally configurable until locally validated.',
        ],
        [
            'key' => 'temperature.review_below',
            'measurement' => 'temperature',
            'test_type' => null,
            'threshold_type' => 'review_below',
            'label' => 'Temperature low review threshold',
            'value' => 36,
            'unit' => 'C',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Configurable threshold for review only; not diagnostic by itself.',
        ],
        [
            'key' => 'temperature.review_min',
            'measurement' => 'temperature',
            'test_type' => null,
            'threshold_type' => 'review_min',
            'label' => 'Temperature high review threshold',
            'value' => 38,
            'unit' => 'C',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Configurable threshold for review only; not diagnostic by itself.',
        ],
        [
            'key' => 'temperature.urgent_min',
            'measurement' => 'temperature',
            'test_type' => null,
            'threshold_type' => 'urgent_min',
            'label' => 'Temperature urgent referral threshold',
            'value' => 39,
            'unit' => 'C',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Referral support threshold only; healthcare-worker assessment is required.',
        ],
        [
            'key' => 'heart_rate.review_below',
            'measurement' => 'heart_rate',
            'test_type' => null,
            'threshold_type' => 'review_below',
            'label' => 'Heart rate low review threshold',
            'value' => 60,
            'unit' => 'bpm',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Configurable threshold for review only; not diagnostic by itself.',
        ],
        [
            'key' => 'heart_rate.review_min',
            'measurement' => 'heart_rate',
            'test_type' => null,
            'threshold_type' => 'review_min',
            'label' => 'Heart rate high review threshold',
            'value' => 110,
            'unit' => 'bpm',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Configurable threshold for review only; not diagnostic by itself.',
        ],
        [
            'key' => 'heart_rate.urgent_min',
            'measurement' => 'heart_rate',
            'test_type' => null,
            'threshold_type' => 'urgent_min',
            'label' => 'Heart rate urgent referral threshold',
            'value' => 130,
            'unit' => 'bpm',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Referral support threshold only; healthcare-worker assessment is required.',
        ],
        [
            'key' => 'heart_rate.urgent_below',
            'measurement' => 'heart_rate',
            'test_type' => null,
            'threshold_type' => 'urgent_below',
            'label' => 'Heart rate low urgent referral threshold',
            'value' => 45,
            'unit' => 'bpm',
            'guideline_name' => 'Facility-configurable maternal vital screening rule',
            'guideline_version' => 'Pending partner OB-GYN/facility validation',
            'source_url' => 'https://psmfm.org/web/professional-resources/',
            'notes' => 'Referral support threshold only; healthcare-worker assessment is required.',
        ],
        [
            'key' => 'weight.unusual_below',
            'measurement' => 'weight',
            'test_type' => null,
            'threshold_type' => 'unusual_below',
            'label' => 'Weight confirmation lower threshold',
            'value' => 35,
            'unit' => 'kg',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'ELENA updated 2023; local facility review required',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Weight is logged and trended, not classified by a universal range.',
        ],
        [
            'key' => 'weight.unusual_min',
            'measurement' => 'weight',
            'test_type' => null,
            'threshold_type' => 'unusual_min',
            'label' => 'Weight confirmation upper threshold',
            'value' => 180,
            'unit' => 'kg',
            'guideline_name' => 'WHO Assessment Methods During Pregnancy',
            'guideline_version' => 'ELENA updated 2023; local facility review required',
            'source_url' => 'https://www.who.int/tools/elena/interventions/assessment-methods-pregnancy',
            'notes' => 'Weight is logged and trended, not classified by a universal range.',
        ],
    ],
];
